version: '3'

services:
  backend:
    container_name: nfl_backend
    build:
      context: nfl_backend
    ports:
      - 4000:4000
      
  frontend:
    container_name: nfl_frontend
    build:
      context: nfl_frontend
      args:
        BACKEND_URI: http://localhost:4000
    ports:
      - 8080:80
